name: push
on: [push]
jobs:
  list-contents:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls ./src/content/ > ./src/_content.txt
      - if: ${git diff --exit-code src/_content.txt} != ""
      - run: |
          git config --local user.email "antboehler@gmail.com"
          git config --local user.name "AntVil"
          git add ./src/_content.txt
          git commit -m "update _content.txt"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
